- hosts: salt-proxy
  remote_user: root
  tasks:

    - name: 拷贝初始化脚本
      template: src={{ item }} dest=/tmp/{{ item }} owner=root group=root
      with_items:
        - install_lnmp.sh

    - name: 开始安装LNMP
      shell: /bin/sh /tmp/install_lnmp.sh > /tmp/install.log 2>&1

